// @ts-nocheck
// PowerShell backend for host UI automation on Windows.
//
// Windows has no xdotool and no bundled CLI for input, so the actions are done the way the
// no-dependency tools do it: P/Invoke into user32.dll for the pointer and keys (SetCursorPos /
// mouse_event / keybd_event), System.Windows.Forms.SendKeys for text, System.Drawing's
// CopyFromScreen for captures, and Get/Set-Clipboard for the clipboard. Shipping this as one
// version-stamped .ps1 keeps the quoting sane: the server passes typed parameters, never a
// composed command line.
(function (root) {
  const HOST_UI_PS1_VERSION = '1';

  const HOST_UI_PS1 = String.raw`# OpenClaw host UI helper — version __VERSION__
# Generated by openclaw-setup. Edits are overwritten when the version changes.
param(
  [Parameter(Mandatory = $true)][string]$Action,
  [int]$X = -1,
  [int]$Y = -1,
  [int]$ToX = -1,
  [int]$ToY = -1,
  [int]$Amount = 3,
  [string]$Text = '',
  [string]$Button = 'left',
  [int]$Clicks = 1,
  [string]$Path = '',
  [string]$Title = ''
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Windows.Forms, System.Drawing

if (-not ('OpenClawUi' -as [type])) {
  Add-Type -Namespace '' -Name OpenClawUi -MemberDefinition @'
[DllImport("user32.dll")] public static extern bool SetCursorPos(int x, int y);
[DllImport("user32.dll")] public static extern void mouse_event(uint flags, uint dx, uint dy, uint data, int extra);
[DllImport("user32.dll")] public static extern bool SetForegroundWindow(System.IntPtr hWnd);
[DllImport("user32.dll")] public static extern bool ShowWindow(System.IntPtr hWnd, int cmd);
'@
}

$MOUSEEVENTF = @{
  leftdown = 0x0002; leftup = 0x0004;
  rightdown = 0x0008; rightup = 0x0010;
  middledown = 0x0020; middleup = 0x0040;
  wheel = 0x0800; hwheel = 0x01000;
}

function Out-Json($obj) { $obj | ConvertTo-Json -Compress -Depth 6 }

function Move-Pointer([int]$px, [int]$py) {
  if ($px -ge 0 -and $py -ge 0) { [OpenClawUi]::SetCursorPos($px, $py) | Out-Null; Start-Sleep -Milliseconds 40 }
}

function Invoke-Click([string]$btn, [int]$times) {
  $down = $MOUSEEVENTF[($btn + 'down')]
  $up = $MOUSEEVENTF[($btn + 'up')]
  if (-not $down) { throw "unknown button: $btn" }
  for ($i = 0; $i -lt [Math]::Max(1, $times); $i++) {
    [OpenClawUi]::mouse_event($down, 0, 0, 0, 0)
    [OpenClawUi]::mouse_event($up, 0, 0, 0, 0)
    Start-Sleep -Milliseconds 60
  }
}

# SendKeys needs its own escaping: + ^ % ~ ( ) { } [ ] are modifiers there, so literal text has
# to be wrapped in braces or the bot's message silently turns into shortcuts.
function ConvertTo-SendKeysLiteral([string]$s) {
  $sb = New-Object System.Text.StringBuilder
  foreach ($ch in $s.ToCharArray()) {
    if ('+^%~(){}[]'.Contains($ch)) { [void]$sb.Append('{' + $ch + '}') }
    elseif ($ch -eq [char]10) { [void]$sb.Append('{ENTER}') }
    elseif ($ch -eq [char]9) { [void]$sb.Append('{TAB}') }
    elseif ($ch -eq [char]13) { }
    else { [void]$sb.Append($ch) }
  }
  $sb.ToString()
}

# "ctrl+shift+t" / "enter" / "cmd+a" (cmd is mapped to ctrl on Windows) → SendKeys syntax.
function ConvertTo-SendKeysCombo([string]$combo) {
  $named = @{
    enter = '{ENTER}'; return = '{ENTER}'; tab = '{TAB}'; esc = '{ESC}'; escape = '{ESC}';
    backspace = '{BACKSPACE}'; delete = '{DELETE}'; del = '{DELETE}'; home = '{HOME}'; end = '{END}';
    pageup = '{PGUP}'; pagedown = '{PGDN}'; up = '{UP}'; down = '{DOWN}'; left = '{LEFT}'; right = '{RIGHT}';
    space = ' '; f1 = '{F1}'; f2 = '{F2}'; f3 = '{F3}'; f4 = '{F4}'; f5 = '{F5}'; f6 = '{F6}';
    f7 = '{F7}'; f8 = '{F8}'; f9 = '{F9}'; f10 = '{F10}'; f11 = '{F11}'; f12 = '{F12}';
    printscreen = '{PRTSC}'; insert = '{INSERT}';
  }
  $prefix = ''
  $parts = $combo.Split('+') | ForEach-Object { $_.Trim().ToLower() } | Where-Object { $_ }
  $keyPart = ''
  foreach ($p in $parts) {
    switch ($p) {
      'ctrl' { $prefix += '^' }
      'control' { $prefix += '^' }
      'cmd' { $prefix += '^' }      # macOS habit; Windows equivalent is Ctrl
      'meta' { $prefix += '^' }
      'alt' { $prefix += '%' }
      'shift' { $prefix += '+' }
      'win' { $prefix += '' }       # SendKeys cannot press Win; use the Windows key combos below
      default { $keyPart = $p }
    }
  }
  if (-not $keyPart) { throw "no key in combo: $combo" }
  $mapped = if ($named.ContainsKey($keyPart)) { $named[$keyPart] } else { $keyPart }
  $prefix + $mapped
}

switch ($Action) {
  'screen_size' {
    $b = [System.Windows.Forms.SystemInformation]::VirtualScreen
    Out-Json @{ ok = $true; width = $b.Width; height = $b.Height; left = $b.Left; top = $b.Top }
  }
  'screenshot' {
    if (-not $Path) { throw 'screenshot needs -Path' }
    $b = [System.Windows.Forms.SystemInformation]::VirtualScreen
    $bmp = New-Object System.Drawing.Bitmap $b.Width, $b.Height
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.CopyFromScreen($b.Left, $b.Top, 0, 0, $bmp.Size)
    $dir = Split-Path -Parent $Path
    if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    $bmp.Save($Path, [System.Drawing.Imaging.ImageFormat]::Png)
    $g.Dispose(); $bmp.Dispose()
    Out-Json @{ ok = $true; path = $Path; width = $b.Width; height = $b.Height }
  }
  'mouse_move' { Move-Pointer $X $Y; Out-Json @{ ok = $true; x = $X; y = $Y } }
  'click' { Move-Pointer $X $Y; Invoke-Click $Button $Clicks; Out-Json @{ ok = $true; button = $Button; clicks = $Clicks } }
  'drag' {
    Move-Pointer $X $Y
    [OpenClawUi]::mouse_event($MOUSEEVENTF['leftdown'], 0, 0, 0, 0)
    Start-Sleep -Milliseconds 80
    Move-Pointer $ToX $ToY
    [OpenClawUi]::mouse_event($MOUSEEVENTF['leftup'], 0, 0, 0, 0)
    Out-Json @{ ok = $true; from = @($X, $Y); to = @($ToX, $ToY) }
  }
  'scroll' {
    Move-Pointer $X $Y
    $ticks = [Math]::Max(1, [Math]::Abs($Amount))
    $delta = if ($Amount -lt 0) { -120 } else { 120 }
    for ($i = 0; $i -lt $ticks; $i++) {
      [OpenClawUi]::mouse_event($MOUSEEVENTF['wheel'], 0, 0, [uint32]([int]$delta -band 0xFFFFFFFF), 0)
      Start-Sleep -Milliseconds 40
    }
    Out-Json @{ ok = $true; amount = $Amount }
  }
  'type' {
    [System.Windows.Forms.SendKeys]::SendWait((ConvertTo-SendKeysLiteral $Text))
    Out-Json @{ ok = $true; typed = $Text.Length }
  }
  'key' {
    foreach ($combo in ($Text -split '\s+' | Where-Object { $_ })) {
      [System.Windows.Forms.SendKeys]::SendWait((ConvertTo-SendKeysCombo $combo))
      Start-Sleep -Milliseconds 60
    }
    Out-Json @{ ok = $true; keys = $Text }
  }
  'clipboard_get' { Out-Json @{ ok = $true; text = (Get-Clipboard -Raw) } }
  'clipboard_set' { Set-Clipboard -Value $Text; Out-Json @{ ok = $true; length = $Text.Length } }
  'windows' {
    $list = Get-Process | Where-Object { $_.MainWindowTitle } |
      Select-Object -First 40 @{n = 'title'; e = { $_.MainWindowTitle } }, @{n = 'process'; e = { $_.ProcessName } }, Id
    Out-Json @{ ok = $true; windows = @($list) }
  }
  'focus' {
    if (-not $Title) { throw 'focus needs -Title' }
    $proc = Get-Process | Where-Object { $_.MainWindowTitle -like "*$Title*" } | Select-Object -First 1
    if (-not $proc) { Out-Json @{ ok = $false; error = "no window matching: $Title" }; break }
    [OpenClawUi]::ShowWindow($proc.MainWindowHandle, 9) | Out-Null   # SW_RESTORE
    [OpenClawUi]::SetForegroundWindow($proc.MainWindowHandle) | Out-Null
    Out-Json @{ ok = $true; focused = $proc.MainWindowTitle }
  }
  default { Out-Json @{ ok = $false; error = "unknown action: $Action" } }
}
`.replace('__VERSION__', HOST_UI_PS1_VERSION);

  const api = { HOST_UI_PS1, HOST_UI_PS1_VERSION };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  root.__openclawHostUiPs1 = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
