const fs = require('fs');
const setup = fs.readFileSync('dist/setup.js', 'utf8');
const cli = fs.readFileSync('dist/cli.js', 'utf8');
console.log('1:', setup.includes("arr.push('call npm install -g 9router || goto :fail');"));
console.log('2:', setup.includes('function native9RouterServerEntryLookup() {'));
console.log('3:', setup.includes('return "node -e '));
console.log('4:', !setup.includes('return "node -p '));
console.log('5:', setup.includes("oc-start9r.ps1"));
console.log('6:', setup.includes('NINE_ROUTER_BIN="$(command -v 9router)"'));
console.log('7:', setup.includes('"$NINE_ROUTER_BIN" -n -H 0.0.0.0 -p 20128 --skip-update'));
console.log('8:', setup.includes("const p=path.join(process.env.DATA_DIR||'.9router','db.json');"));
console.log('9:', setup.includes('nohup env DATA_DIR="$PWD/.9router" node ./.9router/9router-smart-route-sync.js > /tmp/9router-sync.log 2>&1 &'));
console.log('10:', setup.includes('set "PROJECT_DIR='));
console.log('11:', setup.includes('set "OPENCLAW_HOME=%PROJECT_DIR%\\\\.openclaw"'));
console.log('12:', setup.includes('set "OPENCLAW_STATE_DIR=%PROJECT_DIR%\\\\.openclaw"'));
console.log('13:', setup.includes('set "DATA_DIR=%PROJECT_DIR%\\\\.9router"'));
